name: Build
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-manual:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: digitize
        shell: bash -l {0}
        run: |
          cd data
          make
      - name: install echemdb
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: mkdocs
        shell: bash -l {0}
        run: |
          # Since no browser is installed during this CI run, plotly fails to
          # produce HTML output, see https://github.com/plotly/plotly.py/blob/2c2dd6ab2eeff73c782457f33c590c1d09a97625/packages/python/plotly/plotly/io/_renderers.py#L532
          export PLOTLY_RENDERER=browser
          mkdocs build --strict
          mv data generated/website/
          # Disable further processing by GitHub
          touch generated/website/.nojekyll
      - name: build documentation
        shell: bash -l {0}
        run: |
          cd doc
          make html
      - name: fix permissions
        shell: bash -l {0}
        run: |
          # Strangely, the linkchecker modules are installed writable and linkchecker then refuses to load them.
          chmod -R a-w `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
      - name: detect broken links
        shell: bash -l {0}
        run: |
          python -m http.server 8880 --directory generated &
          sleep 1
          # We check for broken links:
          # * ignore fonts.gstatic.com which is mentioned by a link preconnect tag that linkchecker does not parse correctly.
          linkchecker --check-extern --no-robots --ignore fonts.gstatic.com http://localhost:8880/website/ --ignore-url=https://doi.org/10.1002/chem.201803418
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: generated/website
          TARGET_FOLDER: ""
        if: ${{ github.event_name == 'push' }}
      - name: doctest against generated website data
        shell: bash -l {0}
        run: |
          # Create a ZIP archive similar to the one automatically rovided by GitHub.
          mkdir website-gh-pages
          cp -R generated/website/data website-gh-pages/
          zip -r generated/website/website-gh-pages.zip website-gh-pages

          # Run tests against the new ZIP archive.
          export ECHEMDB_DATABASE_URL=http://localhost:8880/website/website-gh-pages.zip
          pytest -n auto --doctest-plus --remote-data --doctest-modules echemdb

env:
  MAKEFLAGS: -j2
